# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven & ElasticSearch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
        
    - name: Configure sysctl
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=26214
        
    - name: install curl
      run: |
        sudo apt-get update
        sudo apt-get install -y curl docker

    - name: Runs Elasticsearch
      uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: 7.6.0
    - name: check ElasticSearch running
      run: curl -XGET "localhost:9200/_cat/nodes?v&pretty"
    - name: check cluster stats
      run: curl -XGET "localhost:9200/_cluster/stats?pretty=true"

    - name: Build with Maven
      run: mvn -B package --file pom.xml    
